### ISSUE TITLE
SIMPLE-CQUEUE does not work in SBCL 

### ISSUE THREAD

**Issue by xach** [oconnore/queues#2]
The following code gives me an error in SBCL 1.3.10:

    (let ((q (queues:make-queue :simple-cqueue)))
      (queues:qpush q 42)
      (queues:qpop q))

The backtrace looks like this:

    Recursive lock attempt #<SB-THREAD:MUTEX "queue-lock" owner: #<SB-THREAD:THREAD "repl-thread" RUNNING {1002E58003}>>.
       [Condition of type SIMPLE-ERROR]

    Restarts:
     0: [RETRY] Retry SLIME REPL evaluation request.
     1: [*ABORT] Return to SLIME's top level.
     2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1002E58003}>)

    Backtrace:
      0: (SB-THREAD::%TRY-MUTEX #<unavailable argument> #<unavailable argument>)
      1: (SB-THREAD:GRAB-MUTEX #<SB-THREAD:MUTEX "queue-lock" owner: #<SB-THREAD:THREAD "repl-thread" RUNNING {1002E58003}>> :WAITP T :TIMEOUT NIL)
      2: ((FLET #:WITHOUT-INTERRUPTS-BODY-359 :IN SB-THREAD::CALL-WITH-MUTEX))
      3: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN QUEUES:QSIZE) {6A4CBFB}> #<SB-THREAD:MUTEX "queue-lock" owner: #<SB-THREAD:THREAD "repl-thread" RUNNING {1002E58003}>> NIL T..
      4: ((:METHOD QUEUES:QSIZE (QUEUES:SIMPLE-CQUEUE)) #<QUEUES:SIMPLE-CQUEUE 42 [1]>) [fast-method]
      5: ((:METHOD QUEUES:QPOP (QUEUES:SIMPLE-QUEUE)) #<QUEUES:SIMPLE-CQUEUE 42 [1]> NIL) [fast-method]
      6: ((FLET #:WITHOUT-INTERRUPTS-BODY-359 :IN SB-THREAD::CALL-WITH-MUTEX))
      7: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN QUEUES:QPOP) {6A4CE2B}> #<SB-THREAD:MUTEX "queue-lock" owner: #<SB-THREAD:THREAD "repl-thread" RUNNING {1002E58003}>> NIL T ..
      8: ((:METHOD QUEUES:QPOP (QUEUES:SIMPLE-CQUEUE)) #<QUEUES:SIMPLE-CQUEUE 42 [1]>) [fast-method]
      9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (LET ((Q #)) (QUEUES:QPUSH Q 42) (QUEUES:QPOP Q)) #<NULL-LEXENV>)
     10: (EVAL (LET ((Q #)) (QUEUES:QPUSH Q 42) (QUEUES:QPOP Q)))

Switch WITH-LOCK-HELD to WITH-RECURSIVE-LOCK-HELD in cqueue.lisp helps, but is that the right fix?

**Comment by oconnore** [comment]
Hi Zach,

I think I was expecting that [declaring a recursive lock](https://github.com/oconnore/queues/blob/master/cqueue.lisp#L20-L22) would result recursive behavior at `#'with-lock-held`. I guess that's not the case. 

Yes, I think changing to `with-recursive-lock-held` would do it. 

https://github.com/oconnore/queues/commit/47d4da65e9ea20953b74aeeab7e89a831b66bc94

Let me know if this helps.

(Also, a little bit depressing that this is being reported almost 5 years later 😆, but better late than never.)

**Comment by oconnore** [comment]
(I'll close this and you can re-open if there's more to do)
